Help commands added.
edualb/Tibro pull request #12
Opened 2019-02-03 01:50 UTC by edualb

* Code Refactoring;
* '!help' or '!h' commands implemented #11 .

2019-02-03 02:53 UTC, arxdsilva commented
if you comment like `fix #11`, the issue will get closed automatically after merging.

2019-02-03 02:58 UTC, arxdsilva requested changes

2019-02-03 02:58 UTC, arxdsilva commented on buscaMonstros.js
> +  let url = servidor == 1 ? urlValhalla : urlThor;
this is pretty nice but lets be more declarative.

2019-02-04 10:33 UTC, edualb commented
fix #11

2019-02-04 13:25 UTC, arxdsilva approved these changes

2019-02-04 13:26 UTC, merged